config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  resources :home, only: [:index]
  resources :microposts, only: %i(create destroy)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class='footer col-md-12'>
  <nav>
    <ul>
      <li><%= link_to 'About', '#' %></li>
      <li><%= link_to 'Contact', '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='container'>
    <%= link_to 'Micropost', home_index_path, id: 'logo' %>
    <nav>
      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to 'Home', home_index_path %></li>
        <li><%= link_to 'Help', '#' %></li>
        <% if logged_in? %>
            <li><%= link_to 'Users',users_path %></li>
            <li class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                Account <b class='caret'></b>
              </a>
              <ul class='dropdown-menu'>
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li class='divider'></li>
                <li>
                  <%= link_to 'log out', logout_path, method: 'delete' %>
                </li>
              </ul>
        <% else %>
            </li>
        <li><%= link_to 'Log_in', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Micropost app</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    </div>
    <div class='container'>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>